import Swal from "sweetalert2";

export const createEmptyRegistrationForm = (schoolPeriod: string = "2026-2027") => ({
  nama: "",
  nisn: "",
  nik: "",
  tempatLahir: "",
  tglLahir: "",
  jenisKelamin: "",
  agama: "",
  kewarganegaraan: "",
  alamat: "",
  rtRw: "",
  kelurahan: "",
  kecamatan: "",
  kodePos: "",
  whatsapp: "",
  email: "",
  tinggalDengan: "",
  transportasi: "",
  tinggiBadan: "",
  beratBadan: "",
  jarakSekolah: "",
  jarakKm: "",
  waktuJam: "",
  waktuMenit: "",
  jumlahSaudara: "",
  golonganDarah: "",
  penyakitDiderita: "",
  kebutuhanKhusus: [],
  jenisPrestasi: [],
  tingkatPrestasi: [],
  uraianPrestasi: "",
  tahunPrestasi: "",
  penyelenggara: "",
  jenisBeasiswa: [],
  uraianBeasiswa: "",
  tahunMulaiBeasiswa: "",
  tahunSelesaiBeasiswa: "",
  namaAyah: "",
  tempatLahirAyah: "",
  tglLahirAyah: "",
  agamaAyah: "",
  kewarganegaraanAyah: "WNI",
  pendidikanAyah: "",
  pekerjaanAyah: "",
  penghasilanAyah: "",
  alamatAyah: "",
  rtrwAyah: "",
  kelurahanAyah: "",
  kecamatanAyah: "",
  kodePosAyah: "",
  statusAyah: "Masih Hidup",
  namaIbu: "",
  tempatLahirIbu: "",
  tglLahirIbu: "",
  agamaIbu: "",
  kewarganegaraanIbu: "WNI",
  pendidikanIbu: "",
  pekerjaanIbu: "",
  penghasilanIbu: "",
  alamatIbu: "",
  rtrwIbu: "",
  kelurahanIbu: "",
  kecamatanIbu: "",
  kodePosIbu: "",
  statusIbu: "Masih Hidup",
  namaWali: "",
  tempatLahirWali: "",
  tglLahirWali: "",
  agamaWali: "",
  kewarganegaraanWali: "WNI",
  pendidikanWali: "",
  pekerjaanWali: "",
  penghasilanWali: "",
  alamatWali: "",
  rtrwWali: "",
  kelurahanWali: "",
  kecamatanWali: "",
  kodePosWali: "",
  statusWali: "Masih Hidup",
  teleponOrtu: "",
  sekolahAsal: "",
  tglLulus: "",
  noIjazah: "",
  noSKHUN: "",
  noPesertaUN: "",
  lamaBelajar: "",
  pindahanDari: "",
  alasanPindah: "",
  diterimaKelas: "",
  diterimaTanggal: "",
  jurusan1: "",
  hobi: [],
  citaCita: "",
  nilaiUSTeori: "",
  nilaiUSPraktik: "",
  nilaiMuatanLokal: "",
  alasanMemilih: "",
  citaCitaSetelahLulus: "",
  pelajaranDisenangi: "",
  punyaKPS: "Tidak",
  noKPS: "",
  punyaKIP: "Tidak",
  noKIP: "",
  alasanDisenangi: "",
  kesulitanBelajar: "",
  perkelahian: "",
  ketPerkelahian: "",
  narkoba: "",
  ketNarkoba: "",
  pelanggaranLain: "",
  ketPelanggaranLain: "",
  janjiTaat: "",
  janjiSanksi: "",
  janjiAkrab: "",
  janjiBelajar: "",
  janjiNamaBaik: "",
  deklarasi: false,
  periode: schoolPeriod,
  berkasFotoOk: false,
  berkasFotoFile: null,
  berkasFotoName: "",
  berkasFotoBase64: "",
  berkasPrestasiBase64: "",
});

export const handleResetRegistration = async ({
  setIsSuccess,
  setSuccessData,
  setSubmittedCandidate,
  setWizardStep,
  setFormData,
  schoolPeriod,
}: {
  setIsSuccess: (val: boolean) => void;
  setSuccessData: (val: any) => void;
  setSubmittedCandidate: (val: any) => void;
  setWizardStep: (val: number) => void;
  setFormData: (val: any) => void;
  schoolPeriod: string;
}) => {
  const result = await Swal.fire({
    title: 'Konfirmasi',
    text: "Apakah Anda ingin mendaftarkan calon siswa baru lainnya?",
    icon: 'warning',
    showCancelButton: true,
    confirmButtonText: 'Ya',
    cancelButtonText: 'Batal'
  });
  if (result.isConfirmed) {
    localStorage.removeItem('ppdb_registration_success');
    setIsSuccess(false);
    setSuccessData(null);
    setSubmittedCandidate(null);
    setWizardStep(1);
    setFormData(createEmptyRegistrationForm(schoolPeriod));
  }
};
